export * from './assessments.service';
import { AssessmentsService } from './assessments.service';
export * from './assets.service';
import { AssetsService } from './assets.service';
export * from './companies.service';
import { CompaniesService } from './companies.service';
export * from './systemGroups.service';
import { SystemGroupsService } from './systemGroups.service';
export * from './tenants.service';
import { TenantsService } from './tenants.service';
export * from './upload.service';
import { UploadService } from './upload.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './vulnerabilities.service';
import { VulnerabilitiesService } from './vulnerabilities.service';
export const APIS = [AssessmentsService, AssetsService, CompaniesService, SystemGroupsService, TenantsService, UploadService, UserService, VulnerabilitiesService];
