/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic


import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class ApiUploadBody { 


    /**
     * Item CsV
     */
    @Expose()
    file!: Blob;

    /**
     * Description: Item CsV
     * datatype: Blob
     * datatypeWithEnum: Blob
     * file: Blob   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<ApiUploadBody> = {}) {
         
            
                    init.file ? this.file = init.file : null
               
    }

    static   getForm(data?: ApiUploadBody | ApiUploadBody[] | null): FormGroup {


        if(!data) {
            return ApiUploadBody.getFormGroup(new ApiUploadBody());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => ApiUploadBody.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  ApiUploadBody.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: ApiUploadBody): FormGroup {
       
        return new FormGroup({           
                        file: new FormControl(data?.file, [])
        });
    }
  

}