/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { AssessmentLifecycleStatus } from './assessmentLifecycleStatus';
import { Company } from './company';
import { NamedBaseModel } from './namedBaseModel';
import { RiskResponseLifecycleStatus } from './riskResponseLifecycleStatus';

/**
 * model.mustache
 *
 * Assessment model
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class Assessment extends NamedBaseModel { 


    /**
     * Created date of the Assessment
     */
    @Expose()
    created!: string;
    @Expose()
    lifecycle_status!: AssessmentLifecycleStatus;
    @Expose()
    risk_response_lifecycle_status!: RiskResponseLifecycleStatus;
    /**
     * Company's id of the Assessment
     */
    @Expose()
    company_id!: number;
    @Expose()
    company!: Company;

    /**
     * Description: Created date of the Assessment
     * datatype: string
     * datatypeWithEnum: string
     * created: string   
     */
    /**
     * datatype: AssessmentLifecycleStatus
     * datatypeWithEnum: AssessmentLifecycleStatus
     * lifecycle_status: AssessmentLifecycleStatus   
     */
    /**
     * datatype: RiskResponseLifecycleStatus
     * datatypeWithEnum: RiskResponseLifecycleStatus
     * risk_response_lifecycle_status: RiskResponseLifecycleStatus   
     */
    /**
     * Description: Company's id of the Assessment
     * datatype: number
     * datatypeWithEnum: number
     * company_id: number   
     */
    /**
     * datatype: Company
     * datatypeWithEnum: Company
     * company: Company   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<Assessment> = {}) {
        super(init)  
            
                    init.created ? this.created = init.created : null,
               
                        init.lifecycle_status ? this.lifecycle_status = init.lifecycle_status : null,
                        init.risk_response_lifecycle_status ? this.risk_response_lifecycle_status = init.risk_response_lifecycle_status : null,
            
                    init.company_id ? this.company_id = init.company_id : null,
               
                        this.company = new Company(init.company || {})
    }

    static override  getForm(data?: Assessment | Assessment[] | null): FormGroup {


        if(!data) {
            return Assessment.getFormGroup(new Assessment());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => Assessment.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  Assessment.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static override  getFormGroup(data?: Assessment): FormGroup {
       
        return new FormGroup({           
                        created: new FormControl(data?.created, []),
                        lifecycle_status: new FormControl(data?.lifecycle_status, []),
                        risk_response_lifecycle_status: new FormControl(data?.risk_response_lifecycle_status, []),
                        company_id: new FormControl(data?.company_id, [Validators.pattern('^[0-9]*$')]),
                        company: (() => { 
                            const fg = Company.getForm(data?.company);
                            fg.addValidators([]);
                            return fg;
                        })()
        });
    }
  

}