/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { Asset } from './asset';
import { Meta } from './meta';

/**
 * model.mustache
 *
 * AssetPagingResource
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class AssetPagingResource { 


    /**
     * Data wrapper
     */
    @Expose()
    @Type(() => Asset)
    data!: Array<Asset>;
    @Expose()
    meta!: Meta;

    /**
     * Description: Data wrapper
     * Complex type: Asset
     * datatype: Array&lt;Asset&gt;
     * datatypeWithEnum: Array&lt;Asset&gt;
     * data: Array<Asset>   
     */
    /**
     * datatype: Meta
     * datatypeWithEnum: Meta
     * meta: Meta   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<AssetPagingResource> = {}) {
         
                            this.data = init.data?.map(x => new Asset(x)) || [] ,
                            this.meta = new Meta(init.meta || {})
    }

    static   getForm(data?: AssetPagingResource | AssetPagingResource[] | null): FormGroup {


        if(!data) {
            return AssetPagingResource.getFormGroup(new AssetPagingResource());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => AssetPagingResource.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  AssetPagingResource.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: AssetPagingResource): FormGroup {
       
        return new FormGroup({           
                        meta: (() => { 
                            const fg = Meta.getForm(data?.meta);
                            fg.addValidators([]);
                            return fg;
                        })()
        });
    }
  

}