/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { AssessmentLifecycleStatus } from './assessmentLifecycleStatus';
import { AssessmentTreatment } from './assessmentTreatment';
import { RiskResponseLifecycleStatus } from './riskResponseLifecycleStatus';

import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class AssessmentStoreRequest { 


    /**
     * Note of the Assessment
     */
    @Expose()
    note!: string;
    @Expose()
    lifecycle_status!: AssessmentLifecycleStatus;
    @Expose()
    treatment!: AssessmentTreatment;
    /**
     * The company id of the Assessment
     */
    @Expose()
    company_id: number | undefined;
    /**
     * The system group id of the Assessment
     */
    @Expose()
    system_group_id: number | undefined;
    /**
     * The asset id of the Assessment
     */
    @Expose()
    asset_id: number | undefined;
    /**
     * Risk Response of the Assessment
     */
    @Expose()
    risk_response!: string;
    @Expose()
    risk_response_lifecycle_status!: RiskResponseLifecycleStatus;

    /**
     * Description: Note of the Assessment
     * datatype: string
     * datatypeWithEnum: string
     * note: string   
     */
    /**
     * datatype: AssessmentLifecycleStatus
     * datatypeWithEnum: AssessmentLifecycleStatus
     * lifecycle_status: AssessmentLifecycleStatus   
     */
    /**
     * datatype: AssessmentTreatment
     * datatypeWithEnum: AssessmentTreatment
     * treatment: AssessmentTreatment   
     */
    /**
     * Description: The company id of the Assessment
     * Nullable property
     * datatype: number
     * datatypeWithEnum: number
     * company_id: number   
     */
    /**
     * Description: The system group id of the Assessment
     * Nullable property
     * datatype: number
     * datatypeWithEnum: number
     * system_group_id: number   
     */
    /**
     * Description: The asset id of the Assessment
     * Nullable property
     * datatype: number
     * datatypeWithEnum: number
     * asset_id: number   
     */
    /**
     * Description: Risk Response of the Assessment
     * datatype: string
     * datatypeWithEnum: string
     * risk_response: string   
     */
    /**
     * datatype: RiskResponseLifecycleStatus
     * datatypeWithEnum: RiskResponseLifecycleStatus
     * risk_response_lifecycle_status: RiskResponseLifecycleStatus   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<AssessmentStoreRequest> = {}) {
         
            
                    init.note ? this.note = init.note : null,
               
                        init.lifecycle_status ? this.lifecycle_status = init.lifecycle_status : null,
                        init.treatment ? this.treatment = init.treatment : null,
            
                    init.company_id ? this.company_id = init.company_id : null,
               
            
                    init.system_group_id ? this.system_group_id = init.system_group_id : null,
               
            
                    init.asset_id ? this.asset_id = init.asset_id : null,
               
            
                    init.risk_response ? this.risk_response = init.risk_response : null,
               
                        init.risk_response_lifecycle_status ? this.risk_response_lifecycle_status = init.risk_response_lifecycle_status : null
    }

    static   getForm(data?: AssessmentStoreRequest | AssessmentStoreRequest[] | null): FormGroup {


        if(!data) {
            return AssessmentStoreRequest.getFormGroup(new AssessmentStoreRequest());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => AssessmentStoreRequest.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  AssessmentStoreRequest.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: AssessmentStoreRequest): FormGroup {
       
        return new FormGroup({           
                        note: new FormControl(data?.note, []),
                        lifecycle_status: new FormControl(data?.lifecycle_status, []),
                        treatment: new FormControl(data?.treatment, []),
                        company_id: new FormControl(data?.company_id, [Validators.pattern('^[0-9]*$')]),
                        system_group_id: new FormControl(data?.system_group_id, [Validators.pattern('^[0-9]*$')]),
                        asset_id: new FormControl(data?.asset_id, [Validators.pattern('^[0-9]*$')]),
                        risk_response: new FormControl(data?.risk_response, []),
                        risk_response_lifecycle_status: new FormControl(data?.risk_response_lifecycle_status, [])
        });
    }
  

}