/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { Assessment } from './assessment';

import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class AssessmentsResource { 


    /**
     * Data wrapper
     */
    @Expose()
    @Type(() => Assessment)
    data!: Array<Assessment>;

    /**
     * Description: Data wrapper
     * Complex type: Assessment
     * datatype: Array&lt;Assessment&gt;
     * datatypeWithEnum: Array&lt;Assessment&gt;
     * data: Array<Assessment>   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<AssessmentsResource> = {}) {
         
                            this.data = init.data?.map(x => new Assessment(x)) || [] 
    }

    static   getForm(data?: AssessmentsResource | AssessmentsResource[] | null): FormGroup {


        if(!data) {
            return AssessmentsResource.getFormGroup(new AssessmentsResource());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => AssessmentsResource.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  AssessmentsResource.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: AssessmentsResource): FormGroup {
       
        return new FormGroup({           
        });
    }
  

}