/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic


export type AssessmentTreatment = 'ACCEPT' | 'MITIGATE' | 'TRANSFER' | 'AVOID';

export const AssessmentTreatment = {
    ACCEPT: 'ACCEPT' as AssessmentTreatment,
    MITIGATE: 'MITIGATE' as AssessmentTreatment,
    TRANSFER: 'TRANSFER' as AssessmentTreatment,
    AVOID: 'AVOID' as AssessmentTreatment
};