/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { AssessmentLifecycleStatus } from './assessmentLifecycleStatus';

import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class AssessmentUpdateRequest { 


    /**
     * Name of the new Assessment
     */
    @Expose()
    name!: string;
    @Expose()
    lifecycle_status!: AssessmentLifecycleStatus;
    /**
     * The company id of the Assessment
     */
    @Expose()
    company_id!: number;
    /**
     * The system group id of the Assessment
     */
    @Expose()
    system_group_id!: number;
    /**
     * The asset id of the Assessment
     */
    @Expose()
    asset_id!: number;

    /**
     * Description: Name of the new Assessment
     * datatype: string
     * datatypeWithEnum: string
     * name: string   
     */
    /**
     * datatype: AssessmentLifecycleStatus
     * datatypeWithEnum: AssessmentLifecycleStatus
     * lifecycle_status: AssessmentLifecycleStatus   
     */
    /**
     * Description: The company id of the Assessment
     * datatype: number
     * datatypeWithEnum: number
     * company_id: number   
     */
    /**
     * Description: The system group id of the Assessment
     * datatype: number
     * datatypeWithEnum: number
     * system_group_id: number   
     */
    /**
     * Description: The asset id of the Assessment
     * datatype: number
     * datatypeWithEnum: number
     * asset_id: number   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<AssessmentUpdateRequest> = {}) {
         
            
                    init.name ? this.name = init.name : null,
               
                        init.lifecycle_status ? this.lifecycle_status = init.lifecycle_status : null,
            
                    init.company_id ? this.company_id = init.company_id : null,
               
            
                    init.system_group_id ? this.system_group_id = init.system_group_id : null,
               
            
                    init.asset_id ? this.asset_id = init.asset_id : null
               
    }

    static   getForm(data?: AssessmentUpdateRequest | AssessmentUpdateRequest[] | null): FormGroup {


        if(!data) {
            return AssessmentUpdateRequest.getFormGroup(new AssessmentUpdateRequest());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => AssessmentUpdateRequest.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  AssessmentUpdateRequest.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: AssessmentUpdateRequest): FormGroup {
       
        return new FormGroup({           
                        name: new FormControl(data?.name, []),
                        lifecycle_status: new FormControl(data?.lifecycle_status, []),
                        company_id: new FormControl(data?.company_id, [Validators.pattern('^[0-9]*$')]),
                        system_group_id: new FormControl(data?.system_group_id, [Validators.pattern('^[0-9]*$')]),
                        asset_id: new FormControl(data?.asset_id, [Validators.pattern('^[0-9]*$')])
        });
    }
  

}