/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { Company } from './company';

/**
 * model.mustache
 *
 * CompanyResource
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class CompanyResource { 


    /**
     * Data wrapper
     */
    @Expose()
    @Type(() => Company)
    data!: Array<Company>;

    /**
     * Description: Data wrapper
     * Complex type: Company
     * datatype: Array&lt;Company&gt;
     * datatypeWithEnum: Array&lt;Company&gt;
     * data: Array<Company>   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<CompanyResource> = {}) {
         
                            this.data = init.data?.map(x => new Company(x)) || [] 
    }

    static   getForm(data?: CompanyResource | CompanyResource[] | null): FormGroup {


        if(!data) {
            return CompanyResource.getFormGroup(new CompanyResource());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => CompanyResource.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  CompanyResource.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: CompanyResource): FormGroup {
       
        return new FormGroup({           
        });
    }
  

}