/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic


import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class CompanyStoreRequest { 


    /**
     * Name of the new company
     */
    @Expose()
    name!: string;
    /**
     * The tenant id of the company
     */
    @Expose()
    tenant_id!: number;

    /**
     * Description: Name of the new company
     * datatype: string
     * datatypeWithEnum: string
     * name: string   
     */
    /**
     * Description: The tenant id of the company
     * datatype: number
     * datatypeWithEnum: number
     * tenant_id: number   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<CompanyStoreRequest> = {}) {
         
            
                    init.name ? this.name = init.name : null,
               
            
                    init.tenant_id ? this.tenant_id = init.tenant_id : null
               
    }

    static   getForm(data?: CompanyStoreRequest | CompanyStoreRequest[] | null): FormGroup {


        if(!data) {
            return CompanyStoreRequest.getFormGroup(new CompanyStoreRequest());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => CompanyStoreRequest.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  CompanyStoreRequest.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: CompanyStoreRequest): FormGroup {
       
        return new FormGroup({           
                        name: new FormControl(data?.name, []),
                        tenant_id: new FormControl(data?.tenant_id, [Validators.pattern('^[0-9]*$')])
        });
    }
  

}