/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic


import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class LoginRequest { 


    /**
     * Email of of User
     */
    @Expose()
    email!: string;
    /**
     * Users password
     */
    @Expose()
    password!: string;

    /**
     * Description: Email of of User
     * datatype: string
     * datatypeWithEnum: string
     * email: string   
     */
    /**
     * Description: Users password
     * datatype: string
     * datatypeWithEnum: string
     * password: string   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<LoginRequest> = {}) {
         
            
                    init.email ? this.email = init.email : null,
               
            
                    init.password ? this.password = init.password : null
               
    }

    static   getForm(data?: LoginRequest | LoginRequest[] | null): FormGroup {


        if(!data) {
            return LoginRequest.getFormGroup(new LoginRequest());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => LoginRequest.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  LoginRequest.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: LoginRequest): FormGroup {
       
        return new FormGroup({           
                        email: new FormControl(data?.email, []),
                        password: new FormControl(data?.password, [])
        });
    }
  

}