/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { BaseModel } from './baseModel';

/**
 * model.mustache
 *
 * NamedBaseModel
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class NamedBaseModel extends BaseModel { 


    /**
     * Name of the User
     */
    @Expose()
    name!: string;

    /**
     * Description: Name of the User
     * datatype: string
     * datatypeWithEnum: string
     * name: string   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<NamedBaseModel> = {}) {
        super(init)  
            
                    init.name ? this.name = init.name : null
               
    }

    static override  getForm(data?: NamedBaseModel | NamedBaseModel[] | null): FormGroup {


        if(!data) {
            return NamedBaseModel.getFormGroup(new NamedBaseModel());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => NamedBaseModel.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  NamedBaseModel.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static override  getFormGroup(data?: NamedBaseModel): FormGroup {
       
        return new FormGroup({           
                        name: new FormControl(data?.name, [])
        });
    }
  

}