/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic


export type RiskResponseLifecycleStatus = 'OPEN' | 'IN_PROGRESS' | 'CLOSED';

export const RiskResponseLifecycleStatus = {
    OPEN: 'OPEN' as RiskResponseLifecycleStatus,
    INPROGRESS: 'IN_PROGRESS' as RiskResponseLifecycleStatus,
    CLOSED: 'CLOSED' as RiskResponseLifecycleStatus
};