/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { Assessment } from './assessment';
import { NamedBaseModel } from './namedBaseModel';
import { RiskResponseLifecycleStatus } from './riskResponseLifecycleStatus';

/**
 * model.mustache
 *
 * RiskResponse model
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class RiskResponse extends NamedBaseModel { 


    /**
     * Created date of the RiskResponse
     */
    @Expose()
    created!: string;
    @Expose()
    lifecycle_status!: RiskResponseLifecycleStatus;
    /**
     * Assessment's id of the RiskResponse
     */
    @Expose()
    assessment_id!: number;
    @Expose()
    assessment!: Assessment;

    /**
     * Description: Created date of the RiskResponse
     * datatype: string
     * datatypeWithEnum: string
     * created: string   
     */
    /**
     * datatype: RiskResponseLifecycleStatus
     * datatypeWithEnum: RiskResponseLifecycleStatus
     * lifecycle_status: RiskResponseLifecycleStatus   
     */
    /**
     * Description: Assessment's id of the RiskResponse
     * datatype: number
     * datatypeWithEnum: number
     * assessment_id: number   
     */
    /**
     * datatype: Assessment
     * datatypeWithEnum: Assessment
     * assessment: Assessment   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<RiskResponse> = {}) {
        super(init)  
            
                    init.created ? this.created = init.created : null,
               
                        init.lifecycle_status ? this.lifecycle_status = init.lifecycle_status : null,
            
                    init.assessment_id ? this.assessment_id = init.assessment_id : null,
               
                        this.assessment = new Assessment(init.assessment || {})
    }

    static override  getForm(data?: RiskResponse | RiskResponse[] | null): FormGroup {


        if(!data) {
            return RiskResponse.getFormGroup(new RiskResponse());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => RiskResponse.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  RiskResponse.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static override  getFormGroup(data?: RiskResponse): FormGroup {
       
        return new FormGroup({           
                        created: new FormControl(data?.created, []),
                        lifecycle_status: new FormControl(data?.lifecycle_status, []),
                        assessment_id: new FormControl(data?.assessment_id, [Validators.pattern('^[0-9]*$')]),
                        assessment: (() => { 
                            const fg = Assessment.getForm(data?.assessment);
                            fg.addValidators([]);
                            return fg;
                        })()
        });
    }
  

}