/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { RiskResponse } from './riskResponse';

import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class RiskResponseResource { 


    /**
     * Data wrapper
     */
    @Expose()
    @Type(() => RiskResponse)
    data!: Array<RiskResponse>;

    /**
     * Description: Data wrapper
     * Complex type: RiskResponse
     * datatype: Array&lt;RiskResponse&gt;
     * datatypeWithEnum: Array&lt;RiskResponse&gt;
     * data: Array<RiskResponse>   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<RiskResponseResource> = {}) {
         
                            this.data = init.data?.map(x => new RiskResponse(x)) || [] 
    }

    static   getForm(data?: RiskResponseResource | RiskResponseResource[] | null): FormGroup {


        if(!data) {
            return RiskResponseResource.getFormGroup(new RiskResponseResource());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => RiskResponseResource.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  RiskResponseResource.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: RiskResponseResource): FormGroup {
       
        return new FormGroup({           
        });
    }
  

}