/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { BaseModel } from './baseModel';
import { Company } from './company';

/**
 * model.mustache
 *
 * ScanImportJob model
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class ScanImportJob extends BaseModel { 


    @Expose()
    company!: Company;

    /**
     * datatype: Company
     * datatypeWithEnum: Company
     * company: Company   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<ScanImportJob> = {}) {
        super(init)  
                        this.company = new Company(init.company || {})
    }

    static override  getForm(data?: ScanImportJob | ScanImportJob[] | null): FormGroup {


        if(!data) {
            return ScanImportJob.getFormGroup(new ScanImportJob());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => ScanImportJob.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  ScanImportJob.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static override  getFormGroup(data?: ScanImportJob): FormGroup {
       
        return new FormGroup({           
                        company: (() => { 
                            const fg = Company.getForm(data?.company);
                            fg.addValidators([]);
                            return fg;
                        })()
        });
    }
  

}