/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { Meta } from './meta';
import { ScanImportJob } from './scanImportJob';

/**
 * model.mustache
 *
 * ScanImportJobPagingResource
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class ScanImportJobPagingResource { 


    /**
     * Data wrapper
     */
    @Expose()
    @Type(() => ScanImportJob)
    data!: Array<ScanImportJob>;
    @Expose()
    meta!: Meta;

    /**
     * Description: Data wrapper
     * Complex type: ScanImportJob
     * datatype: Array&lt;ScanImportJob&gt;
     * datatypeWithEnum: Array&lt;ScanImportJob&gt;
     * data: Array<ScanImportJob>   
     */
    /**
     * datatype: Meta
     * datatypeWithEnum: Meta
     * meta: Meta   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<ScanImportJobPagingResource> = {}) {
         
                            this.data = init.data?.map(x => new ScanImportJob(x)) || [] ,
                            this.meta = new Meta(init.meta || {})
    }

    static   getForm(data?: ScanImportJobPagingResource | ScanImportJobPagingResource[] | null): FormGroup {


        if(!data) {
            return ScanImportJobPagingResource.getFormGroup(new ScanImportJobPagingResource());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => ScanImportJobPagingResource.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  ScanImportJobPagingResource.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: ScanImportJobPagingResource): FormGroup {
       
        return new FormGroup({           
                        meta: (() => { 
                            const fg = Meta.getForm(data?.meta);
                            fg.addValidators([]);
                            return fg;
                        })()
        });
    }
  

}