/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { ScanImportJob } from './scanImportJob';

/**
 * model.mustache
 *
 * ScanImportJobResource
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class ScanImportJobResource { 


    @Expose()
    data!: ScanImportJob;

    /**
     * datatype: ScanImportJob
     * datatypeWithEnum: ScanImportJob
     * data: ScanImportJob   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<ScanImportJobResource> = {}) {
         
                            this.data = new ScanImportJob(init.data || {})
    }

    static   getForm(data?: ScanImportJobResource | ScanImportJobResource[] | null): FormGroup {


        if(!data) {
            return ScanImportJobResource.getFormGroup(new ScanImportJobResource());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => ScanImportJobResource.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  ScanImportJobResource.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: ScanImportJobResource): FormGroup {
       
        return new FormGroup({           
                        data: (() => { 
                            const fg = ScanImportJob.getForm(data?.data);
                            fg.addValidators([]);
                            return fg;
                        })()
        });
    }
  

}