/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic


import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class SystemGroupUpdateRequest { 


    /**
     * Name of the new system group
     */
    @Expose()
    name!: string;

    /**
     * Description: Name of the new system group
     * datatype: string
     * datatypeWithEnum: string
     * name: string   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<SystemGroupUpdateRequest> = {}) {
         
            
                    init.name ? this.name = init.name : null
               
    }

    static   getForm(data?: SystemGroupUpdateRequest | SystemGroupUpdateRequest[] | null): FormGroup {


        if(!data) {
            return SystemGroupUpdateRequest.getFormGroup(new SystemGroupUpdateRequest());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => SystemGroupUpdateRequest.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  SystemGroupUpdateRequest.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: SystemGroupUpdateRequest): FormGroup {
       
        return new FormGroup({           
                        name: new FormControl(data?.name, [])
        });
    }
  

}