/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { Meta } from './meta';
import { Tenant } from './tenant';

/**
 * model.mustache
 *
 * TenantPagingResource
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class TenantPagingResource { 


    /**
     * Data wrapper
     */
    @Expose()
    @Type(() => Tenant)
    data!: Array<Tenant>;
    @Expose()
    meta!: Meta;

    /**
     * Description: Data wrapper
     * Complex type: Tenant
     * datatype: Array&lt;Tenant&gt;
     * datatypeWithEnum: Array&lt;Tenant&gt;
     * data: Array<Tenant>   
     */
    /**
     * datatype: Meta
     * datatypeWithEnum: Meta
     * meta: Meta   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<TenantPagingResource> = {}) {
         
                            this.data = init.data?.map(x => new Tenant(x)) || [] ,
                            this.meta = new Meta(init.meta || {})
    }

    static   getForm(data?: TenantPagingResource | TenantPagingResource[] | null): FormGroup {


        if(!data) {
            return TenantPagingResource.getFormGroup(new TenantPagingResource());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => TenantPagingResource.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  TenantPagingResource.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: TenantPagingResource): FormGroup {
       
        return new FormGroup({           
                        meta: (() => { 
                            const fg = Meta.getForm(data?.meta);
                            fg.addValidators([]);
                            return fg;
                        })()
        });
    }
  

}