/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { Tenant } from './tenant';

/**
 * model.mustache
 *
 * TenantResource
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class TenantResource { 


    @Expose()
    data!: Tenant;

    /**
     * datatype: Tenant
     * datatypeWithEnum: Tenant
     * data: Tenant   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<TenantResource> = {}) {
         
                        this.data = new Tenant(init.data || {})
    }

    static   getForm(data?: TenantResource | TenantResource[] | null): FormGroup {


        if(!data) {
            return TenantResource.getFormGroup(new TenantResource());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => TenantResource.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  TenantResource.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: TenantResource): FormGroup {
       
        return new FormGroup({           
                        data: (() => { 
                            const fg = Tenant.getForm(data?.data);
                            fg.addValidators([]);
                            return fg;
                        })()
        });
    }
  

}