/**
 * API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Type, Expose } from 'class-transformer';
// @dynamic

import { User } from './user';

/**
 * model.mustache
 *
 * UserResource
 */
import { Observable }                                        from 'rxjs';
import { AbstractControl, FormControl, FormGroup, FormArray, Validators }                            from '@angular/forms';

export class UserResource { 


    @Expose()
    data!: User;

    /**
     * datatype: User
     * datatypeWithEnum: User
     * data: User   
     */

    // validations?: Map<string, Array<{[key: string]: string}>> = new Map<string, Array<{[key: string]: string}>>();

    constructor(init: Partial<UserResource> = {}) {
         
                        this.data = new User(init.data || {})
    }

    static   getForm(data?: UserResource | UserResource[] | null): FormGroup {


        if(!data) {
            return UserResource.getFormGroup(new UserResource());
        }

         if(Array.isArray(data)) {
            let arrayForm = new FormArray<any>([]);
            
            if(data.length > 0) {
                arrayForm =  new FormArray<any>(data.map(item => UserResource.getFormGroup(item)));                
            }
            return new FormGroup({
                arrayForm
            });        
        } else {
             return  UserResource.getFormGroup(data);
        }       
     
    }

     /**
   * Get FormGroup
   *
   * @param {object} data
   * @returns {FormGroup}
   */
  static   getFormGroup(data?: UserResource): FormGroup {
       
        return new FormGroup({           
                        data: (() => { 
                            const fg = User.getForm(data?.data);
                            fg.addValidators([]);
                            return fg;
                        })()
        });
    }
  

}